import Head from 'next/head';
import styles from './Layout.module.css';
const Layout = ({ children }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Chatbot Tele</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>{children}</main>
        </div>
    );
};
export default Layout;
